language: elixir
services:
  - postgresql
elixir:
  - 1.10.2
otp_release:
  - 21.0
install:
  - mix local.hex --force && mix deps.get
before_script:
  - mix local.rebar --force && mix ecto.create
script:
  - mix test
